# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: proxl - Protein Cross-linking Database
email: proxl-help@yeastrc.org
author: Michael Riffle
description: > # "Write an awesome description for your new site here. 
  Proxl is a platform for analyzing, visualizing, and sharing protein cross-linking mass spectrometry proteomics data.
copyright: 'Copyright &copy; 2017 Michael Riffle. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: external-link
    text: Use Proxl
    url: https://www.yeastrc.org/proxl_public/
  - icon: question-circle
    text: Documentation
    url: http://www.yeastrc.org/proxl_docs/
  - icon: github
    text: Source Code
    url: https://github.com/yeastrc/proxl-web-app
